[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
monopoly_program = "GMDedNzaiCffFmBNVBDUzd6Ub6XLQ4xhoWfswBRmYqbG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "key.json"

[scripts]
test = ""
